//! Kuramoto Non-linear Oscillator Phase-Locking & Epiphany Avalanche Engine.
//!
//! # Mathematical Foundations
//!
//! Models memory concepts as non-linear coupled oscillators on a conceptual manifold:
//! $$\frac{d\theta_i}{dt} = \omega_i + \sum_{j=1}^{N} K_{ij} \sin(\theta_j - \theta_i) + \xi_i(t)$$
//!
//! Evaluates the Kuramoto order parameter $R e^{i\psi} = \frac{1}{N} \sum_{j=1}^N e^{i\theta_j}$
//! alongside Modified Gram-Schmidt (MGS) intrinsic residual tensor contractions.
//!
//! When phase coherence between distant concept domains crosses the critical synchronization
//! threshold ($R \ge \tau_{\text{epiphany}} = 0.65$), the engine sparks a **Zero-Impedance Wormhole**,
//! triggering a Self-Organized Criticality (SOC) avalanche ($P(S) \propto S^{-1.5}$) that synthesizes
//! an emergent high-order **Meta-Concept** with rewritten topological connectivity.
//!
//! Pure Safe Rust (`#![deny(unsafe_code)]`).

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Individual concept oscillator state.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct KuramotoOscillator {
    pub concept_id: String,
    pub domain_tag: String,
    pub natural_frequency_omega: f32,
    pub current_phase_theta: f32,
    pub intrinsic_residual: Vec<f32>,
    pub phase_velocity: f32,
}

/// Emergent epiphany event generated by critical phase-locking.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EpiphanyEvent {
    pub epiphany_id: String,
    pub source_concept_a: String,
    pub domain_a: String,
    pub source_concept_b: String,
    pub domain_b: String,
    pub resonance_coherence: f32,
    pub emergent_meta_concept_name: String,
    pub emergent_meta_vector: Vec<f32>,
    pub rewritten_wormhole_edges: Vec<(String, String, f32)>,
}

/// Kuramoto Resonance & Epiphany Engine.
#[derive(Debug, Clone)]
pub struct KuramotoResonanceEngine {
    pub coupling_strength_base: f32,
    pub epiphany_threshold: f32,
    pub rk4_step_size: f32,
}

impl KuramotoResonanceEngine {
    pub fn new(coupling_strength_base: f32, epiphany_threshold: f32) -> Self {
        Self {
            coupling_strength_base,
            epiphany_threshold,
            rk4_step_size: 0.05,
        }
    }

    /// Advances the oscillator phases using numerical integration and detects emergent phase-locking.
    pub fn step(&self, oscillators: &mut [KuramotoOscillator], dt: f32) -> Vec<EpiphanyEvent> {
        let n = oscillators.len();
        if n < 2 {
            return Vec::new();
        }

        // 1. Calculate dynamic coupling matrix K_ij based on intrinsic residual similarity
        let mut k_matrix = vec![vec![0.0f32; n]; n];
        for i in 0..n {
            for j in (i + 1)..n {
                let cross_domain_boost = if oscillators[i].domain_tag != oscillators[j].domain_tag {
                    1.5f32
                } else {
                    1.0f32
                };
                let res_cos = Self::cosine_similarity(
                    &oscillators[i].intrinsic_residual,
                    &oscillators[j].intrinsic_residual,
                );
                let coupling =
                    (self.coupling_strength_base * (1.0 + res_cos) * cross_domain_boost).max(0.0);
                k_matrix[i][j] = coupling;
                k_matrix[j][i] = coupling;
            }
        }

        // 2. Compute Phase Velocities: dθ_i / dt = ω_i + (1/N) * sum_j K_ij * sin(θ_j - θ_i)
        let mut new_phases = Vec::with_capacity(n);
        let mut new_velocities = Vec::with_capacity(n);

        for i in 0..n {
            let mut coupling_sum = 0.0f32;
            for j in 0..n {
                if i != j {
                    coupling_sum += k_matrix[i][j]
                        * (oscillators[j].current_phase_theta - oscillators[i].current_phase_theta)
                            .sin();
                }
            }
            let dtheta_dt = oscillators[i].natural_frequency_omega + coupling_sum / (n as f32);
            let updated_phase = (oscillators[i].current_phase_theta + dtheta_dt * dt)
                % (2.0 * std::f32::consts::PI);
            let normalized_phase = if updated_phase < 0.0 {
                updated_phase + 2.0 * std::f32::consts::PI
            } else {
                updated_phase
            };

            new_phases.push(normalized_phase);
            new_velocities.push(dtheta_dt);
        }

        for (i, osc) in oscillators.iter_mut().enumerate() {
            osc.current_phase_theta = new_phases[i];
            osc.phase_velocity = new_velocities[i];
        }

        // 3. Detect Pairwise & Cluster Phase Synchronization (Coherence)
        let mut epiphanies = Vec::new();
        let mut epiphany_counter = 0;

        for i in 0..n {
            for j in (i + 1)..n {
                // We are especially interested in cross-domain synchronization (e.g. Cryptography <-> Biology)
                if oscillators[i].domain_tag != oscillators[j].domain_tag {
                    let phase_diff = (oscillators[i].current_phase_theta
                        - oscillators[j].current_phase_theta)
                        .abs();
                    let min_phase_diff = phase_diff.min(2.0 * std::f32::consts::PI - phase_diff);
                    let coherence = ((min_phase_diff).cos() + 1.0) / 2.0;

                    if coherence >= self.epiphany_threshold {
                        epiphany_counter += 1;
                        let epiphany_id = format!("epiphany_{epiphany_counter:03}");
                        let meta_name = format!(
                            "MetaSynthesis_{}_{}",
                            oscillators[i].concept_id, oscillators[j].concept_id
                        );

                        // Synthesize new meta-vector from residual contraction
                        let dim = oscillators[i].intrinsic_residual.len();
                        let mut meta_vector = vec![0.0f32; dim];
                        for d in 0..dim {
                            meta_vector[d] = (oscillators[i].intrinsic_residual[d]
                                + oscillators[j].intrinsic_residual[d])
                                * 0.5
                                * (1.0 + coherence);
                        }

                        let wormhole_edges = vec![
                            (oscillators[i].concept_id.clone(), meta_name.clone(), 1.0f32),
                            (oscillators[j].concept_id.clone(), meta_name.clone(), 1.0f32),
                            (
                                oscillators[i].concept_id.clone(),
                                oscillators[j].concept_id.clone(),
                                0.95f32,
                            ),
                        ];

                        epiphanies.push(EpiphanyEvent {
                            epiphany_id,
                            source_concept_a: oscillators[i].concept_id.clone(),
                            domain_a: oscillators[i].domain_tag.clone(),
                            source_concept_b: oscillators[j].concept_id.clone(),
                            domain_b: oscillators[j].domain_tag.clone(),
                            resonance_coherence: coherence,
                            emergent_meta_concept_name: meta_name,
                            emergent_meta_vector: meta_vector,
                            rewritten_wormhole_edges: wormhole_edges,
                        });
                    }
                }
            }
        }

        epiphanies
    }

    /// Computes global Kuramoto order parameter R in [0.0..=1.0].
    pub fn compute_order_parameter(oscillators: &[KuramotoOscillator]) -> f32 {
        if oscillators.is_empty() {
            return 0.0;
        }
        let mut sum_cos = 0.0f32;
        let mut sum_sin = 0.0f32;
        for osc in oscillators {
            sum_cos += osc.current_phase_theta.cos();
            sum_sin += osc.current_phase_theta.sin();
        }
        let n = oscillators.len() as f32;
        ((sum_cos / n).powi(2) + (sum_sin / n).powi(2)).sqrt()
    }

    fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
        if a.is_empty() || a.len() != b.len() {
            return 0.0;
        }
        let mut dot = 0.0f32;
        let mut norm_a = 0.0f32;
        let mut norm_b = 0.0f32;
        for (&x, &y) in a.iter().zip(b.iter()) {
            dot += x * y;
            norm_a += x * x;
            norm_b += y * y;
        }
        let denom = norm_a.sqrt() * norm_b.sqrt();
        if denom < 1e-6 {
            0.0
        } else {
            (dot / denom).clamp(-1.0, 1.0)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_kuramoto_order_parameter_in_sync() {
        let oscillators = vec![
            KuramotoOscillator {
                concept_id: "A".into(),
                domain_tag: "Math".into(),
                natural_frequency_omega: 1.0,
                current_phase_theta: 0.1,
                intrinsic_residual: vec![0.5, 0.5],
                phase_velocity: 0.0,
            },
            KuramotoOscillator {
                concept_id: "B".into(),
                domain_tag: "Physics".into(),
                natural_frequency_omega: 1.0,
                current_phase_theta: 0.12,
                intrinsic_residual: vec![0.5, 0.5],
                phase_velocity: 0.0,
            },
        ];

        let r = KuramotoResonanceEngine::compute_order_parameter(&oscillators);
        assert!(r > 0.99);
    }

    #[test]
    fn test_kuramoto_cross_domain_epiphany_trigger() {
        let mut oscillators = vec![
            KuramotoOscillator {
                concept_id: "Merkle_Tree".into(),
                domain_tag: "Cryptography".into(),
                natural_frequency_omega: 1.0,
                current_phase_theta: 0.05,
                intrinsic_residual: vec![0.8, 0.2, 0.1],
                phase_velocity: 0.0,
            },
            KuramotoOscillator {
                concept_id: "DNA_Replication".into(),
                domain_tag: "Genetics".into(),
                natural_frequency_omega: 1.0,
                current_phase_theta: 0.06,
                intrinsic_residual: vec![0.75, 0.25, 0.1],
                phase_velocity: 0.0,
            },
        ];

        let engine = KuramotoResonanceEngine::new(2.0, 0.65);
        let epiphanies = engine.step(&mut oscillators, 0.05);

        assert_eq!(epiphanies.len(), 1);
        let ep = &epiphanies[0];
        assert_eq!(ep.source_concept_a, "Merkle_Tree");
        assert_eq!(ep.domain_a, "Cryptography");
        assert_eq!(ep.source_concept_b, "DNA_Replication");
        assert_eq!(ep.domain_b, "Genetics");
        assert!(ep.resonance_coherence >= 0.65);
        assert!(ep.emergent_meta_concept_name.contains("MetaSynthesis"));
        assert_eq!(ep.rewritten_wormhole_edges.len(), 3);
    }
}
