pub mod emergence;
pub mod emotion;
pub mod world_model;
pub mod curiosity;
pub mod intent_brier;
pub mod streaming;
pub mod presence;
pub mod prompt_assembler;
pub mod continuation;
pub mod observer_capture;
pub mod dream;
pub mod epistemic;
pub mod blueprint;
pub mod consciousness;
pub mod cognition;
pub mod asi;
pub mod motivation;
pub mod value;
pub mod perception;
pub mod experience;
pub mod capability;
pub mod confidence;
pub mod audit;
pub mod memory_extractor;
pub mod emotion_memory;
pub mod goal;
pub mod timeline;
pub mod session_log;
pub mod tone;
pub mod onering;
pub mod agent_trace;
pub mod approval_requests;
pub mod daily_summary;
pub mod milestone;
pub mod memory_graph;
pub mod oracle;
pub mod meta_thinking;
pub mod prompt_cache;
pub mod constitution_gate;
pub mod principles;
pub mod judicator;
pub mod packs;
pub mod partner;
pub mod reflexion;
pub mod streaming_chat;

pub use dream::{DreamEngine, DreamReport, EntityTriplet, DreamRehearsalResult};
pub use epistemic::{EpistemicHealer, FailureIncident};


